INSERT INTO reports (
    id,
    tracking_code,
    title,
    description,
    category,
    latitude,
    longitude,
    status,
    created_at
)
SELECT
    gen_random_uuid()::text,
    'TEST-' || lpad(gs::text, 5, '0'),

    '[TEST] Bejelentés #' || gs,
    'Autogenerated test report #' || gs,

    (ARRAY['safety','infrastructure','homeless','other'])[1 + floor(random()*4)],

    -- 🇭🇺 better spread: Hungary bounds
    45.7 + random() * (48.7 - 45.7) AS latitude,
    16.0 + random() * (23.1 - 16.0) AS longitude,

    (ARRAY['open','in_progress','resolved','invalid'])[1 + floor(random()*4)],

    NOW() - (random() * interval '30 days')
FROM generate_series(1, :count::int) gs;